### ISSUE TITLE
(java 7) It seems that onAccepted or onDenied are not called

### ISSUE THREAD

**Issue by Bloubloublou** [florent37/RuntimePermission#11]
Hi, i hope you could help me...
Here is my code  (basically the same as in readme)

    `askPermission(this)
                .ask(new PermissionListener() {

                    @Override
                    public void onAccepted(RuntimePermission runtimePermission, List<String> accepted) {
                        //all permissions already granted or just grantedyour action
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Log.d("PERMISSIONS", "accepted");
                            }
                        });
                    }

                    @Override
                    public void onDenied(RuntimePermission runtimePermission, List<String> denied, List<String> foreverDenied) {
                        //the list of denied permissions
                        for (String permission : denied) {
                            Log.d("PERMISSIONS", permission + " denied");
                        }
                        //permission denied, but you can ask again, eg:

                        //the list of forever denied permissions, user has check 'never ask again'
                        for (String permission : foreverDenied) {
                            Log.d("PERMISSIONS", permission + " forever denied");
                        }
                        // you need to open setting manually if you really need it
                        //runtimePermission.goToSettings();
                    }
                });`

The permission is asked but there is no log "accepted" or "denied" (when I try to call a pop up dialog it is not displayed) . Why that?

**Comment by iman2420** [comment]
Yeah **onAccepted()** not call in first run. Why ?

**Comment by florent37** [comment]
can you try with the last version ?

**Comment by iman2420** [comment]
I tried to use it.
But the problem was not resolved.
I finally deleted the library
