### ISSUE TITLE
Calling accepted when all permission denied with Never Ask Again

### ISSUE THREAD

**Issue by aashu09** [florent37/RuntimePermission#12]
Hi,
I am using Runtime permission for Kotlin but When it asks for permissions and I check Never Ask Again for all permissions then deny permissions, so it goes into the accepted function.

Actual - It goes to accepted function when I check Never Ask Permission and deny them

Expected - It should go into the denied function when anyone denies all permissions with never ask again.

**Comment by MrThreepwood** [comment]
Do you want to paste your code here. The documentation on the main page is 100% wrong about how the library works on at least one of the examples.

**Comment by florent37** [comment]
can you try with the last version ?
