### ISSUE TITLE
runtime-permission-kotlin : kotlin-stdlib-jre7 is deprecated

### ISSUE THREAD

**Issue by anthony-skr** [florent37/RuntimePermission#13]
Just tried to compile and got :

> C:\Users\*\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jre7\1.2.30\b38fc19e670ebef931fef3ccdcb94eac2b65bb7d\kotlin-stdlib-jre7-1.2.30.jar: **kotlin-stdlib-jre7 is deprecated**. Please use kotlin-stdlib-jdk7 instead

For ones facing the problem just do  :

> implementation("com.github.florent37:runtime-permission-kotlin:$runtime_permission_version") {
          exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jre7'
    }

btw thank you for the library ;)
Cheers!

**Comment by florent37** [comment]
ok i change that
