### ISSUE TITLE
Filed resolve dependencies

### ISSUE THREAD

**Issue by m4xp1** [florent37/RuntimePermission#21]
When i try add this line: implementation 'com.github.florent37:runtime-permission-kotlin:1.0.7'
in my graddle configuration file i get this error: Failed to resolve: org.jetbrains.kotlin:kotlin-stdlib-common:1.3.0-rc-131. For version 1.0.0 everything works right.

**Comment by florent37** [comment]
I updated it to 1.3.0

**Comment by lucasrafagnin** [comment]
Add the last version info to the Readme
