### ISSUE TITLE
Failed to resolve: support-fragment

### ISSUE THREAD

**Issue by iman2420** [florent37/RuntimePermission#8]
I want to `useRuntimePermission `in my app, but after updating android studio to 
```
Android Studio 3.1.2
Build #AI-173.4720617, built on April 14, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
Windows 10 10.0 when I add `implementation 'com.github.florent37:runtime-permission:1.0.1' `dependency into app.gradle file, it will show Failed to resolve: support-fragment
My gradle version is `gradle:3.2.0-alpha01`

**Comment by Zhuinden** [comment]
That is an easy fix, just move `jcenter()` in the repositories to the bottom of the `repositories {` block
