### ISSUE TITLE
askPermission requesting for a fragment activity as its first parameter

### ISSUE THREAD

**Issue by sriramr98** [florent37/RuntimePermission#9]
askPermission method is either requesting a fragment or a FragmentActivity as its first parameter.
I want to use it in an AppCompatActivity.

I am using the new AndroidX extensions for my application.
Update it to support the new AndroidX extensions

Language: Kotlin

**Comment by florent37** [comment]
An appcompat activity already extends FragmentActivity

**Comment by florent37** [comment]
Yes i'll update it because they changed the package

**Comment by sriramr98** [comment]
Yeah I'm aware of that. But I still am getting the error while using the new AndroidX entensions. That's the error I'm reporting.
